### ISSUE TITLE
As an operator I like the cluster to be stateless by using an external postgres

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/bosh-community-stemcell-ci-infra#3]
Use external postgres (provided by google cloud):
- [x] concourse
- [x] credhub

**Comment by rkoster** [comment]
related commit for concourse: https://github.com/rkoster/bosh-community-stemcell-ci-infra/commit/dee727aedd55bf0061f5365b14c325d43d4ced2b

**Comment by yatzek** [comment]
@StefanWutz, @ramonskie we can close this one as well.
