### ISSUE TITLE
enable instanced pipelines

### ISSUE THREAD

**Issue by garethjevans** [cloudfoundry/bosh-community-stemcell-ci-infra#49]
We'd like to see if the new `across` functionality with instanced pipelines provides a better experience with pull requests.

From the release notes:

"The across step now supports dynamic interpolation of values. For instance, this can be combined with the set_pipeline step and instanced pipelines to set a dynamic list of pipelines"

**Comment by rkoster** [comment]
@garethjevans would you be able to create a PR for this?
